<script src="{{ asset('chatzy/assets/js/jquery-3.7.1.min.js') }}"></script>
<script src="{{ asset('chatzy/assets/js/owl.carousel.js') }}"></script>
<script src="{{ asset('chatzy/assets/js/popper.min.js') }}"></script>
<script src="{{ asset('chatzy/assets/js/tippy-bundle.iife.min.js') }}"></script>
<script src="{{ asset('chatzy/assets/js/bootstrap.bundle.min.js') }}"></script>
<script src="{{ asset('chatzy/assets/js/switchery.js') }}"></script>
<script src="{{ asset('chatzy/assets/js/easytimer.min.js') }}">        </script>
<script src="{{ asset('chatzy/assets/js/index.js') }}">        </script>
<script src="{{ asset('chatzy/assets/js/feather-icon/feather.min.js') }}"></script>
<script src="{{ asset('chatzy/assets/js/feather-icon/feather-icon.js') }}"></script>
<script src="{{ asset('chatzy/assets/js/ckeditor/ckeditor.js') }}"></script>
<script src="{{ asset('chatzy/assets/js/ckeditor/styles.js') }}"></script>
<script src="{{ asset('chatzy/assets/js/ckeditor/adapters/jquery.js') }}"></script>
<script src="{{ asset('chatzy/assets/js/ckeditor/ckeditor.custom.js') }}"></script>
<script src="{{ asset('chatzy/assets/js/audio-music.js') }}"></script>
<script src="{{ asset('chatzy/assets/js/tour/intro.js') }}"></script>
<script src="{{ asset('chatzy/assets/js/tour/intro-init.js') }}"></script>
<script src="{{ asset('chatzy/assets/js/jquery.magnific-popup.js') }}"></script>
<script src="{{ asset('chatzy/assets/js/zoom-gallery.js') }}"></script>
<script src="{{ asset('chatzy/assets/js/script.js') }}"></script>
